### Extração dos Dados

In [1]:
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account
from pandas.io import gbq

In [2]:
contratos = pd.read_csv ('tabela_contratos.csv')

In [3]:
contratos

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,inicio_vigencia,termino_vigencia,fk_empresa_contratada
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,4,32,1
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,13,33,2
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,10,33,3
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,6,33,4
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,8,35,5
...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,208,243,65
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,209,244,17
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,212,246,66
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,213,247,67
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,214,248,68

In [4]:
datas = pd.read_csv ('tabela_datas.csv')

In [5]:
datas

     id_data        data
0          1  20/05/2014
1          2  27/09/2014
2          3  28/11/2014
3          4  20/12/2014
4          5  28/12/2014
..       ...         ...
249      250  24/10/2019
250      251  24/10/2020
251      252  05/11/2020
252      253  23/01/2020
253      254  31/09/2017

[254 rows x 2 columns]

In [6]:
empresas = pd.read_csv ('tabela_empresas.csv')

In [7]:
empresas

    id_empresa       nome_empresa
0            1   Thomas Jefferson
1            2      Chaveiro City
2            3       HBL Carimbos
3            4          Claro S/A
4            5  Imprensa Nacional
..         ...                ...
63          64     Nara Comercial
64          65            SESI-DF
65          66              FORMA
66          67      IG Elevadores
67          68  Serôa Construtora

[68 rows x 2 columns]

### Transformação dos Dados

In [8]:
contratos_empresas = contratos.merge(empresas,
                                     left_on = 'fk_empresa_contratada',
                                     right_on = 'id_empresa',
                                     how = 'left')

In [9]:
contratos_empresas

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,inicio_vigencia,termino_vigencia,fk_empresa_contratada,id_empresa,nome_empresa
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,4,32,1,1,Thomas Jefferson
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,13,33,2,2,Chaveiro City
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,10,33,3,3,HBL Carimbos
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,6,33,4,4,Claro S/A
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,8,35,5,5,Imprensa Nacional
...,...,...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,208,243,65,65,SESI-DF
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,209,244,17,17,Central IT
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,212,246,66,66,FORMA
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,213,247,67,67,IG Elevadores
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,214,248,68,68,Serôa Construtora

In [10]:
contratos_empresas_datas = contratos_empresas.merge(datas,
                                     left_on = 'inicio_vigencia',
                                     right_on = 'id_data',
                                     how = 'left')

In [11]:
contratos_empresas_datas

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,inicio_vigencia,termino_vigencia,fk_empresa_contratada,id_empresa,nome_empresa,id_data,data
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,4,32,1,1,Thomas Jefferson,4,20/12/2014
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,13,33,2,2,Chaveiro City,13,26/02/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,10,33,3,3,HBL Carimbos,10,10/02/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,6,33,4,4,Claro S/A,6,01/01/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,8,35,5,5,Imprensa Nacional,8,27/01/2015
...,...,...,...,...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,208,243,65,65,SESI-DF,208,24/07/2020
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,209,244,17,17,Central IT,209,27/07/2020
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,212,246,66,66,FORMA,212,19/08/2020
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,213,247,67,67,IG Elevadores,213,31/08/2020
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,214,248,68,68,Serôa Construtora,214,08/09/2020

In [12]:
contratos_empresas_datas.drop(columns=['id_data','fk_empresa_contratada','inicio_vigencia','id_empresa'], inplace =True)

In [13]:
contratos_empresas_datas

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,termino_vigencia,nome_empresa,data
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,32,Thomas Jefferson,20/12/2014
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,33,Chaveiro City,26/02/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,33,HBL Carimbos,10/02/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,33,Claro S/A,01/01/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,35,Imprensa Nacional,27/01/2015
...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,243,SESI-DF,24/07/2020
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,244,Central IT,27/07/2020
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,246,FORMA,19/08/2020
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,247,IG Elevadores,31/08/2020
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,248,Serôa Construtora,08/09/2020

In [14]:
contratos_empresas_final = contratos_empresas_datas.merge(datas,
                                     left_on = 'termino_vigencia',
                                     right_on = 'id_data',
                                     how = 'left')

In [15]:
contratos_empresas_final

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,termino_vigencia,nome_empresa,data_x,id_data,data_y
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,32,Thomas Jefferson,20/12/2014,32,19/12/2015
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,33,Chaveiro City,26/02/2015,33,31/12/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,33,HBL Carimbos,10/02/2015,33,31/12/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,33,Claro S/A,01/01/2015,33,31/12/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,35,Imprensa Nacional,27/01/2015,35,26/01/2016
...,...,...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,243,SESI-DF,24/07/2020,243,24/07/2021
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,244,Central IT,27/07/2020,244,27/07/2021
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,246,FORMA,19/08/2020,246,19/08/2021
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,247,IG Elevadores,31/08/2020,247,31/08/2021
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,248,Serôa Construtora,08/09/2020,248,08/09/2021

In [16]:
contratos_empresas_final.drop(columns=['termino_vigencia','id_data'], inplace=True)

In [17]:
contratos_empresas_final

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_x,data_y
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,20/12/2014,19/12/2015
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,26/02/2015,31/12/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,10/02/2015,31/12/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,01/01/2015,31/12/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,27/01/2015,26/01/2016
...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,SESI-DF,24/07/2020,24/07/2021
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,Central IT,27/07/2020,27/07/2021
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,FORMA,19/08/2020,19/08/2021
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,IG Elevadores,31/08/2020,31/08/2021
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,Serôa Construtora,08/09/2020,08/09/2021

In [18]:
contratos_empresas_final.rename(columns={'data_x': 'data_inicio_vigencia'},inplace=True)

In [19]:
contratos_empresas_final.rename(columns={'data_y': 'data_termino_vigencia'},inplace=True)

In [20]:
contratos_empresas_final

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_inicio_vigencia,data_termino_vigencia
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,20/12/2014,19/12/2015
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,26/02/2015,31/12/2015
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,10/02/2015,31/12/2015
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,01/01/2015,31/12/2015
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,27/01/2015,26/01/2016
...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,SESI-DF,24/07/2020,24/07/2021
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,Central IT,27/07/2020,27/07/2021
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,FORMA,19/08/2020,19/08/2021
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,IG Elevadores,31/08/2020,31/08/2021
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,Serôa Construtora,08/09/2020,08/09/2021

### Validando os Valores do DataFrame Contratos_empresas_final

In [21]:
contratos_empresas_final.count()

id_contrato              184
nome_contrato            184
objeto_contrato          184
valor_contrato           184
nome_empresa             184
data_inicio_vigencia     184
data_termino_vigencia    184
dtype: int64

In [22]:
contratos_empresas_final.dtypes

id_contrato                int64
nome_contrato             object
objeto_contrato           object
valor_contrato           float64
nome_empresa              object
data_inicio_vigencia      object
data_termino_vigencia     object
dtype: object

In [23]:
contratos_empresas_final.data_inicio_vigencia = pd.to_datetime(contratos_empresas_final.data_inicio_vigencia,
                                                             format='%d/%m/%Y').dt.date

In [24]:
contratos_empresas_final.data_termino_vigencia = pd.to_datetime(contratos_empresas_final.data_termino_vigencia,
                                                             format='%d/%m/%Y').dt.date

ValueError: day is out of range for month

In [ ]:
for i in contratos_empresas_final.data_termino_vigencia:
    print (i)
    print (pd.to_datetime(i))

In [25]:
contratos_empresas_final.data_termino_vigencia = contratos_empresas_final.data_termino_vigencia.str.replace('31/09/2017','30/09/2017')

In [26]:
contratos_empresas_final.data_termino_vigencia = pd.to_datetime(contratos_empresas_final.data_termino_vigencia,
                                                             format='%d/%m/%Y').dt.date

In [27]:
contratos_empresas_final.dtypes

id_contrato                int64
nome_contrato             object
objeto_contrato           object
valor_contrato           float64
nome_empresa              object
data_inicio_vigencia      object
data_termino_vigencia     object
dtype: object

In [28]:
contratos_empresas_final

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_inicio_vigencia,data_termino_vigencia
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,2014-12-20,2015-12-19
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,2015-02-26,2015-12-31
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,2015-02-10,2015-12-31
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,2015-01-01,2015-12-31
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,2015-01-27,2016-01-26
...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,SESI-DF,2020-07-24,2021-07-24
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,Central IT,2020-07-27,2021-07-27
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,FORMA,2020-08-19,2021-08-19
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,IG Elevadores,2020-08-31,2021-08-31
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,Serôa Construtora,2020-09-08,2021-09-08

In [29]:
contratos_empresas_final['tempo_contrato'] = (contratos_empresas_final.data_termino_vigencia - \
                                              contratos_empresas_final.data_inicio_vigencia).dt.days

In [30]:
contratos_empresas_final

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_inicio_vigencia,data_termino_vigencia,tempo_contrato
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,2014-12-20,2015-12-19,364
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,2015-02-26,2015-12-31,308
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,2015-02-10,2015-12-31,324
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,2015-01-01,2015-12-31,364
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,2015-01-27,2016-01-26,364
...,...,...,...,...,...,...,...,...
179,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,SESI-DF,2020-07-24,2021-07-24,365
180,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,Central IT,2020-07-27,2021-07-27,365
181,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,FORMA,2020-08-19,2021-08-19,365
182,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,IG Elevadores,2020-08-31,2021-08-31,365
183,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,Serôa Construtora,2020-09-08,2021-09-08,365

### Validando os valores dos dias de contrato

In [31]:
contratos_empresas_final.tempo_contrato.value_counts()

 365     88
 366     45
 364     10
 1096     8
 730      2
 352      2
 731      2
 0        2
 749      2
 359      2
 750      2
 722      2
 1095     2
 729      2
 350      1
 531      1
 179      1
 182      1
-2        1
 340      1
 353      1
 363      1
 324      1
 339      1
 308      1
 394      1
 295      1
Name: tempo_contrato, dtype: int64

In [32]:
contratos_empresas_final = contratos_empresas_final[contratos_empresas_final.tempo_contrato > 0]

In [33]:
contratos_empresas_final.reset_index(drop=True, inplace=True)

In [34]:
contratos_empresas_final

,id_contrato,nome_contrato,objeto_contrato,valor_contrato,nome_empresa,data_inicio_vigencia,data_termino_vigencia,tempo_contrato
0,1,13/2012,Contratação de Empresa para Ministrar Curso de...,94947.23,Thomas Jefferson,2014-12-20,2015-12-19,364
1,2,Disp. Lic. 1,Prestação de serviço na confecção de Chaves,5234.00,Chaveiro City,2015-02-26,2015-12-31,308
2,3,Disp. Lic. 2,Prestação de serviço na confecção de Carimbos,1800.00,HBL Carimbos,2015-02-10,2015-12-31,324
3,4,32/2014,Serviço de Telefônia Móvel,73915.08,Claro S/A,2015-01-01,2015-12-31,364
4,5,001/2014,Publicações no Diário Oficial da União,45000.00,Imprensa Nacional,2015-01-27,2016-01-26,364
...,...,...,...,...,...,...,...,...
176,180,13/2020,Contratação de serviços ofertados pelo SESI/Si...,134211.84,SESI-DF,2020-07-24,2021-07-24,365
177,181,009/2018,Serviços de Suporte Tecnológico ao Ambiente d...,2107768.42,Central IT,2020-07-27,2021-07-27,365
178,182,16/2020,Aquisição e Instalação de divisórias,5541773.00,FORMA,2020-08-19,2021-08-19,365
179,183,18/2020,Manutenção Preventiva e corretiva dos elevador...,9600.00,IG Elevadores,2020-08-31,2021-08-31,365
180,184,20/2020,Contratação de Serviço comum de engenharia,102600.00,Serôa Construtora,2020-09-08,2021-09-08,365

### Carregamento dos Dados

In [61]:
credentials = service_account.Credentials.from_service_account_file("GBQ.json",
                                                                   scopes=["https://www.googleapis.com/auth/cloud-platform",
                                                                           'https://www.googleapis.com/auth/drive'])

In [64]:
contratos_empresas_final.to_gbq(credentials=credentials,
                                destination_table='etlfinal.etl_csv',
                                if_exists='replace',
                                table_schema=[{'name': 'data_inicio_vigencia', 'type': 'DATE'},
                                             {'name': 'data_termino_vigencia', 'type': 'DATE'}])

100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]